server:
  port: 8080
spring:
  application:
    name: reggie_take_out
    # 数据库连接
  datasource:
    druid:
      # 数据库驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库连接地址 localhost = 127.0.0.1 本机
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      # 用户名
      username: root
      # 密码
      password: root123qwe
  redis:
    # 连接地址
    host: 127.0.0.1
    # 密码 有密码的话,需要输入密码
    # password:
    # 端口号
    port: 6379
    # redis使用的是哪个数据库
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    # id_no -> idNo
    map-underscore-to-camel-case: true
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    db-config:
      # id的生成规则
      id-type: ASSIGN_ID
# 自定义属性
# 配置文件中不是只可以使用由框架提供的配置
# 往往一些项目中的配置,也会由自定义的方式,写到配置文件中
reggie:
  path: /Users/t3rik/Desktop/Image
#logging:
#  level:
#    com.itheima.reggie.mapper: debug